init:
  - dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
  - npm install --global capture-website-cli

configuration: Release

before_build:
- cd src
- nuget restore

image: Visual Studio 2019

build:
  verbosity: minimal
  project: .\src\LogoFX.Practices.IoC.sln

test_script:
  - cd
  - cd ..\devops\test
  - test-all.bat
  - cd ..\..\

artifacts:

  - name: Living Documentation
    path: .\src\LogoFX.Practices.IoC.Specs\bin\Release\LivingDoc.html